USE Master
GO
CREATE DATABASE [445GroupERD]
GO
USE [445GroupERD]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LEVEL]') AND type in (N'U'))
    DROP TABLE [dbo].[LEVEL]
GO
CREATE TABLE [dbo].[LEVEL] (
[LevelID] INTEGER  NOT NULL
, [LevelDescr] VARCHAR(255)  NULL
)
GO

ALTER TABLE [dbo].[LEVEL] ADD CONSTRAINT [LEVEL_PK] PRIMARY KEY CLUSTERED (
[LevelID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOT]') AND type in (N'U'))
    DROP TABLE [dbo].[LOT]
GO
CREATE TABLE [dbo].[LOT] (
[LotID] INTEGER  NOT NULL
, [DistrictID] INTEGER  NULL
, [LotName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[LOT] ADD CONSTRAINT [LOT_PK] PRIMARY KEY CLUSTERED (
[LotID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROVINCE]') AND type in (N'U'))
    DROP TABLE [dbo].[PROVINCE]
GO
CREATE TABLE [dbo].[PROVINCE] (
[ProvinceID] INTEGER  NOT NULL
, [TheatreID] INTEGER  NULL
, [ProvTypeID] INTEGER  NULL
, [ProvinceName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[PROVINCE] ADD CONSTRAINT [PROVINCE_PK] PRIMARY KEY CLUSTERED (
[ProvinceID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EVENT_PLAY_CHAR]') AND type in (N'U'))
    DROP TABLE [dbo].[EVENT_PLAY_CHAR]
GO
CREATE TABLE [dbo].[EVENT_PLAY_CHAR] (
[EventPlayCharID] INTEGER  NOT NULL
, [PlayCharacterID] INTEGER  NULL
, [EventID] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[EVENT_PLAY_CHAR] ADD CONSTRAINT [EVENT_PLAY_CHAR_PK] PRIMARY KEY CLUSTERED (
[EventPlayCharID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[THEATRE]') AND type in (N'U'))
    DROP TABLE [dbo].[THEATRE]
GO
CREATE TABLE [dbo].[THEATRE] (
[TheatreID] INTEGER  NOT NULL
, [TheatreName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[THEATRE] ADD CONSTRAINT [THEATRE_PK] PRIMARY KEY CLUSTERED (
[TheatreID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EVENT_TYPE]') AND type in (N'U'))
    DROP TABLE [dbo].[EVENT_TYPE]
GO
CREATE TABLE [dbo].[EVENT_TYPE] (
[EventTypeID] INTEGER  NOT NULL
, [EventTypeName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[EVENT_TYPE] ADD CONSTRAINT [EVENT_TYPE_PK] PRIMARY KEY CLUSTERED (
[EventTypeID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOCATION]') AND type in (N'U'))
    DROP TABLE [dbo].[LOCATION]
GO
CREATE TABLE [dbo].[LOCATION] (
[LocationID] INTEGER  NOT NULL
, [LocationName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[LOCATION] ADD CONSTRAINT [LOCATION_PK] PRIMARY KEY CLUSTERED (
[LocationID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EVENT]') AND type in (N'U'))
    DROP TABLE [dbo].[EVENT]
GO
CREATE TABLE [dbo].[EVENT] (
[LocationID] INTEGER  NOT NULL
, [EventID] INTEGER  NOT NULL
, [TheatreID] INTEGER  NULL
, [EventTypeID] INTEGER  NULL
, [Price] DOUBLE  NULL
)
GO

ALTER TABLE [dbo].[EVENT] ADD CONSTRAINT [EVENT_PK] PRIMARY KEY CLUSTERED (
[EventID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHARACTER_STATUS]') AND type in (N'U'))
    DROP TABLE [dbo].[CHARACTER_STATUS]
GO
CREATE TABLE [dbo].[CHARACTER_STATUS] (
[CharacterStatusID] INTEGER  NOT NULL
, [StatusName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[CHARACTER_STATUS] ADD CONSTRAINT [CHARACTER_STATUS_PK] PRIMARY KEY CLUSTERED (
[CharacterStatusID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHARACTER_PERMISSION]') AND type in (N'U'))
    DROP TABLE [dbo].[CHARACTER_PERMISSION]
GO
CREATE TABLE [dbo].[CHARACTER_PERMISSION] (
[CharacterPermissionID] INTEGER  NOT NULL
, [Value] CHAR(10)  NULL
, [CharacterID] INTEGER  NULL
, [PermissionID] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[CHARACTER_PERMISSION] ADD CONSTRAINT [CHARACTER_PERMISSION_PK] PRIMARY KEY CLUSTERED (
[CharacterPermissionID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PERMISSION]') AND type in (N'U'))
    DROP TABLE [dbo].[PERMISSION]
GO
CREATE TABLE [dbo].[PERMISSION] (
[PermissionID] INTEGER  NOT NULL
)
GO

ALTER TABLE [dbo].[PERMISSION] ADD CONSTRAINT [PERMISSION_PK] PRIMARY KEY CLUSTERED (
[PermissionID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SKILL]') AND type in (N'U'))
    DROP TABLE [dbo].[SKILL]
GO
CREATE TABLE [dbo].[SKILL] (
[SkillID] INTEGER  NOT NULL
, [SkillName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[SKILL] ADD CONSTRAINT [SKILL_PK] PRIMARY KEY CLUSTERED (
[SkillID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHARACTER_SKILL_LEVEL]') AND type in (N'U'))
    DROP TABLE [dbo].[CHARACTER_SKILL_LEVEL]
GO
CREATE TABLE [dbo].[CHARACTER_SKILL_LEVEL] (
[CharacterSkillID] INTEGER  NOT NULL
, [CharacterID] INTEGER  NULL
, [LevelValue] INTEGER  NULL
, [SkillID] INTEGER  NULL
, [LevelID] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[CHARACTER_SKILL_LEVEL] ADD CONSTRAINT [CHARACTER_SKILL_LEVEL_PK] PRIMARY KEY CLUSTERED (
[CharacterSkillID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PLAYER_STATUS_TYPE]') AND type in (N'U'))
    DROP TABLE [dbo].[PLAYER_STATUS_TYPE]
GO
CREATE TABLE [dbo].[PLAYER_STATUS_TYPE] (
[PlayerStatusTypeID] INTEGER  NOT NULL
, [PlayerStatusTypeName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[PLAYER_STATUS_TYPE] ADD CONSTRAINT [PLAYER_STATUS_TYPE_PK] PRIMARY KEY CLUSTERED (
[PlayerStatusTypeID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PAYMENT]') AND type in (N'U'))
    DROP TABLE [dbo].[PAYMENT]
GO
CREATE TABLE [dbo].[PAYMENT] (
[PaymentID] INTEGER  NOT NULL
, [PaymentTypeID] INTEGER  NULL
, [EventPlayCharID] INTEGER  NOT NULL
)
GO

ALTER TABLE [dbo].[PAYMENT] ADD CONSTRAINT [PAYMENT_PK] PRIMARY KEY CLUSTERED (
[EventPlayCharID]
, [PaymentID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PAYMENT_TYPE]') AND type in (N'U'))
    DROP TABLE [dbo].[PAYMENT_TYPE]
GO
CREATE TABLE [dbo].[PAYMENT_TYPE] (
[PaymentTypeID] INTEGER  NOT NULL
, [PaymentTypeName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[PAYMENT_TYPE] ADD CONSTRAINT [PAYMENT_TYPE_PK] PRIMARY KEY CLUSTERED (
[PaymentTypeID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PLAYER_CHARACTER]') AND type in (N'U'))
    DROP TABLE [dbo].[PLAYER_CHARACTER]
GO
CREATE TABLE [dbo].[PLAYER_CHARACTER] (
[PlayerCharacterID] INTEGER  NOT NULL
, [PlayerID] INTEGER  NULL
, [CharacterID] INTEGER  NULL
, [Date] DATETIME  NULL
, [EventPlayCharID] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[PLAYER_CHARACTER] ADD CONSTRAINT [PLAYER_CHARACTER_PK] PRIMARY KEY CLUSTERED (
[PlayerCharacterID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PLAYER]') AND type in (N'U'))
    DROP TABLE [dbo].[PLAYER]
GO
CREATE TABLE [dbo].[PLAYER] (
[PlayerID] INTEGER  NOT NULL
, [PlayerFname] VARCHAR(60)  NULL
, [PlayerLname] VARCHAR(60)  NULL
, [PlayerDOB] DATETIME  NULL
, [PlayerAddress] VARCHAR(75)  NULL
, [PlayerCity] VARCHAR(75)  NULL
, [PlayerState] VARCHAR(75)  NULL
, [PlayerCountry] VARCHAR(75)  NULL
, [PlayerZIP] VARCHAR(25)  NULL
, [PlayerEmail] VARCHAR(75)  NULL
, [PlayerPhoneNumber] CHAR(8)  NULL
)
GO

ALTER TABLE [dbo].[PLAYER] ADD CONSTRAINT [PLAYER_PK] PRIMARY KEY CLUSTERED (
[PlayerID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PLAYER_STATUS]') AND type in (N'U'))
    DROP TABLE [dbo].[PLAYER_STATUS]
GO
CREATE TABLE [dbo].[PLAYER_STATUS] (
[PlayerStatusID] INTEGER  NOT NULL
, [PlayerID] INTEGER  NULL
, [PlayerStatusTypeID] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[PLAYER_STATUS] ADD CONSTRAINT [PLAYER_STATUS_PK] PRIMARY KEY CLUSTERED (
[PlayerStatusID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHARACTER]') AND type in (N'U'))
    DROP TABLE [dbo].[CHARACTER]
GO
CREATE TABLE [dbo].[CHARACTER] (
[CharacterID] INTEGER  NOT NULL
, [CharacterStatusID] INTEGER  NULL
, [XPcomp] INTEGER  NULL
, [CharName] VARCHAR(50)  NULL
, [CharCulture] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[CHARACTER] ADD CONSTRAINT [CHARACTER_PK] PRIMARY KEY CLUSTERED (
[CharacterID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INVENTORY]') AND type in (N'U'))
    DROP TABLE [dbo].[INVENTORY]
GO
CREATE TABLE [dbo].[INVENTORY] (
[InventoryID] INTEGER  NOT NULL
, [LotID] INTEGER  NULL
, [ItemName] VARCHAR(50)  NULL
, [ItemDescr] VARCHAR(255)  NULL
, [ItemQty] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[INVENTORY] ADD CONSTRAINT [INVENTORY_PK] PRIMARY KEY CLUSTERED (
[InventoryID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROVINCE_RESOURCE]') AND type in (N'U'))
    DROP TABLE [dbo].[PROVINCE_RESOURCE]
GO
CREATE TABLE [dbo].[PROVINCE_RESOURCE] (
[ProvResource] INTEGER  NOT NULL
, [ProvinceID] INTEGER  NULL
, [ResourceID] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[PROVINCE_RESOURCE] ADD CONSTRAINT [PROVINCE_RESOURCE_PK] PRIMARY KEY CLUSTERED (
[ProvResource]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RESOURCE]') AND type in (N'U'))
    DROP TABLE [dbo].[RESOURCE]
GO
CREATE TABLE [dbo].[RESOURCE] (
[ResourceID] INTEGER  NOT NULL
, [ResourceName] VARCHAR(50)  NULL
, [ResourceQty] INTEGER  NULL
, [ResourceTypeID] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[RESOURCE] ADD CONSTRAINT [RESOURCE_PK] PRIMARY KEY CLUSTERED (
[ResourceID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[STRUCTURE_PROVINCE_RESOURCE]') AND type in (N'U'))
    DROP TABLE [dbo].[STRUCTURE_PROVINCE_RESOURCE]
GO
CREATE TABLE [dbo].[STRUCTURE_PROVINCE_RESOURCE] (
[StructProvResID] INTEGER  NOT NULL
, [StructureID] INTEGER  NULL
, [ProvResource] INTEGER  NULL
)
GO

ALTER TABLE [dbo].[STRUCTURE_PROVINCE_RESOURCE] ADD CONSTRAINT [STRUCTURE_PROVINCE_RESOURCE_PK] PRIMARY KEY CLUSTERED (
[StructProvResID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[STRUCTURE]') AND type in (N'U'))
    DROP TABLE [dbo].[STRUCTURE]
GO
CREATE TABLE [dbo].[STRUCTURE] (
[StructureID] INTEGER  NOT NULL
, [StructureName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[STRUCTURE] ADD CONSTRAINT [STRUCTURE_PK] PRIMARY KEY CLUSTERED (
[StructureID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[XP_TRANSACTION]') AND type in (N'U'))
    DROP TABLE [dbo].[XP_TRANSACTION]
GO
CREATE TABLE [dbo].[XP_TRANSACTION] (
[XPID] INTEGER  NOT NULL
, [CharacterID] INTEGER  NULL
, [XPamount] INTEGER  NULL
, [XPdate] DATETIME  NULL
, [XPtransferDescr] VARCHAR(255)  NULL
)
GO

ALTER TABLE [dbo].[XP_TRANSACTION] ADD CONSTRAINT [XP_TRANSACTION_PK] PRIMARY KEY CLUSTERED (
[XPID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROVINCE_TYPE]') AND type in (N'U'))
    DROP TABLE [dbo].[PROVINCE_TYPE]
GO
CREATE TABLE [dbo].[PROVINCE_TYPE] (
[ProvTypeID] INTEGER  NOT NULL
, [ProvinceTypeName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[PROVINCE_TYPE] ADD CONSTRAINT [PROVINCE_TYPE_PK] PRIMARY KEY CLUSTERED (
[ProvTypeID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CITY]') AND type in (N'U'))
    DROP TABLE [dbo].[CITY]
GO
CREATE TABLE [dbo].[CITY] (
[CityID] INTEGER  NOT NULL
, [ProvinceID] INTEGER  NULL
, [CityName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[CITY] ADD CONSTRAINT [CITY_PK] PRIMARY KEY CLUSTERED (
[CityID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DISTRICT]') AND type in (N'U'))
    DROP TABLE [dbo].[DISTRICT]
GO
CREATE TABLE [dbo].[DISTRICT] (
[DistrictID] INTEGER  NOT NULL
, [CityID] INTEGER  NULL
, [DistrictName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[DISTRICT] ADD CONSTRAINT [DISTRICT_PK] PRIMARY KEY CLUSTERED (
[DistrictID]
)
GO
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RESOURCE_TYPE]') AND type in (N'U'))
    DROP TABLE [dbo].[RESOURCE_TYPE]
GO
CREATE TABLE [dbo].[RESOURCE_TYPE] (
[ResourceTypeID] INTEGER  NOT NULL
, [ResourceTypeName] VARCHAR(50)  NULL
)
GO

ALTER TABLE [dbo].[RESOURCE_TYPE] ADD CONSTRAINT [RESOURCE_TYPE_PK] PRIMARY KEY CLUSTERED (
[ResourceTypeID]
)
GO
GO

GO

ALTER TABLE [dbo].[LOT] WITH CHECK ADD CONSTRAINT [DISTRICT_LOT_FK1] FOREIGN KEY (
[DistrictID]
)
REFERENCES [dbo].[DISTRICT] (
[DistrictID]
)
GO

ALTER TABLE [dbo].[PROVINCE] WITH CHECK ADD CONSTRAINT [PROVINCE_TYPE_PROVINCE_FK1] FOREIGN KEY (
[ProvTypeID]
)
REFERENCES [dbo].[PROVINCE_TYPE] (
[ProvTypeID]
)
ALTER TABLE [dbo].[PROVINCE] WITH CHECK ADD CONSTRAINT [THEATRE_PROVINCE_FK1] FOREIGN KEY (
[TheatreID]
)
REFERENCES [dbo].[THEATRE] (
[TheatreID]
)
GO

ALTER TABLE [dbo].[EVENT_PLAY_CHAR] WITH CHECK ADD CONSTRAINT [EVENT_EVENT_PLAY_CHAR_FK1] FOREIGN KEY (
[EventID]
)
REFERENCES [dbo].[EVENT] (
[EventID]
)
GO

GO

GO

GO

ALTER TABLE [dbo].[EVENT] WITH CHECK ADD CONSTRAINT [THEATRE_EVENT_FK1] FOREIGN KEY (
[TheatreID]
)
REFERENCES [dbo].[THEATRE] (
[TheatreID]
)
ALTER TABLE [dbo].[EVENT] WITH CHECK ADD CONSTRAINT [EVENT_TYPE_EVENT_FK1] FOREIGN KEY (
[EventTypeID]
)
REFERENCES [dbo].[EVENT_TYPE] (
[EventTypeID]
)
ALTER TABLE [dbo].[EVENT] WITH CHECK ADD CONSTRAINT [LOCATION_EVENT_FK1] FOREIGN KEY (
[LocationID]
)
REFERENCES [dbo].[LOCATION] (
[LocationID]
)
GO

GO

ALTER TABLE [dbo].[CHARACTER_PERMISSION] WITH CHECK ADD CONSTRAINT [CHARACTER_CHARACTER_PERMISSION_FK1] FOREIGN KEY (
[CharacterID]
)
REFERENCES [dbo].[CHARACTER] (
[CharacterID]
)
ALTER TABLE [dbo].[CHARACTER_PERMISSION] WITH CHECK ADD CONSTRAINT [PERMISSION_CHARACTER_PERMISSION_FK1] FOREIGN KEY (
[PermissionID]
)
REFERENCES [dbo].[PERMISSION] (
[PermissionID]
)
GO

GO

GO

ALTER TABLE [dbo].[CHARACTER_SKILL_LEVEL] WITH CHECK ADD CONSTRAINT [SKILL_CHARACTER_SKILL_LEVEL_FK1] FOREIGN KEY (
[SkillID]
)
REFERENCES [dbo].[SKILL] (
[SkillID]
)
ALTER TABLE [dbo].[CHARACTER_SKILL_LEVEL] WITH CHECK ADD CONSTRAINT [CHARACTER_CHARACTER_SKILL_LEVEL_FK1] FOREIGN KEY (
[CharacterID]
)
REFERENCES [dbo].[CHARACTER] (
[CharacterID]
)
ALTER TABLE [dbo].[CHARACTER_SKILL_LEVEL] WITH CHECK ADD CONSTRAINT [LEVEL_CHARACTER_SKILL_LEVEL_FK1] FOREIGN KEY (
[LevelID]
)
REFERENCES [dbo].[LEVEL] (
[LevelID]
)
GO

GO

ALTER TABLE [dbo].[PAYMENT] WITH CHECK ADD CONSTRAINT [EVENT_PLAY_CHAR_PAYMENT_FK1] FOREIGN KEY (
[EventPlayCharID]
)
REFERENCES [dbo].[EVENT_PLAY_CHAR] (
[EventPlayCharID]
)
ALTER TABLE [dbo].[PAYMENT] WITH CHECK ADD CONSTRAINT [PAYMENT_TYPE_PAYMENT_FK1] FOREIGN KEY (
[PaymentTypeID]
)
REFERENCES [dbo].[PAYMENT_TYPE] (
[PaymentTypeID]
)
GO

GO

ALTER TABLE [dbo].[PLAYER_CHARACTER] WITH CHECK ADD CONSTRAINT [EVENT_PLAY_CHAR_PLAYER_CHARACTER_FK1] FOREIGN KEY (
[EventPlayCharID]
)
REFERENCES [dbo].[EVENT_PLAY_CHAR] (
[EventPlayCharID]
)
ALTER TABLE [dbo].[PLAYER_CHARACTER] WITH CHECK ADD CONSTRAINT [PLAYER_PLAYER_CHARACTER_FK1] FOREIGN KEY (
[PlayerID]
)
REFERENCES [dbo].[PLAYER] (
[PlayerID]
)
ALTER TABLE [dbo].[PLAYER_CHARACTER] WITH CHECK ADD CONSTRAINT [CHARACTER_PLAYER_CHARACTER_FK1] FOREIGN KEY (
[CharacterID]
)
REFERENCES [dbo].[CHARACTER] (
[CharacterID]
)
GO

GO

ALTER TABLE [dbo].[PLAYER_STATUS] WITH CHECK ADD CONSTRAINT [PLAYER_PLAYER_STATUS_FK1] FOREIGN KEY (
[PlayerID]
)
REFERENCES [dbo].[PLAYER] (
[PlayerID]
)
ALTER TABLE [dbo].[PLAYER_STATUS] WITH CHECK ADD CONSTRAINT [PLAYER_STATUS_TYPE_PLAYER_STATUS_FK1] FOREIGN KEY (
[PlayerStatusTypeID]
)
REFERENCES [dbo].[PLAYER_STATUS_TYPE] (
[PlayerStatusTypeID]
)
GO

ALTER TABLE [dbo].[CHARACTER] WITH CHECK ADD CONSTRAINT [CHARACTER_STATUS_CHARACTER_FK1] FOREIGN KEY (
[CharacterStatusID]
)
REFERENCES [dbo].[CHARACTER_STATUS] (
[CharacterStatusID]
)
GO

ALTER TABLE [dbo].[INVENTORY] WITH CHECK ADD CONSTRAINT [LOT_INVENTORY_FK1] FOREIGN KEY (
[LotID]
)
REFERENCES [dbo].[LOT] (
[LotID]
)
GO

ALTER TABLE [dbo].[PROVINCE_RESOURCE] WITH CHECK ADD CONSTRAINT [RESOURCE_PROVINCE_RESOURCE_FK1] FOREIGN KEY (
[ResourceID]
)
REFERENCES [dbo].[RESOURCE] (
[ResourceID]
)
ALTER TABLE [dbo].[PROVINCE_RESOURCE] WITH CHECK ADD CONSTRAINT [PROVINCE_PROVINCE_RESOURCE_FK1] FOREIGN KEY (
[ProvinceID]
)
REFERENCES [dbo].[PROVINCE] (
[ProvinceID]
)
GO

ALTER TABLE [dbo].[RESOURCE] WITH CHECK ADD CONSTRAINT [RESOURCE_TYPE_RESOURCE_FK1] FOREIGN KEY (
[ResourceTypeID]
)
REFERENCES [dbo].[RESOURCE_TYPE] (
[ResourceTypeID]
)
GO

ALTER TABLE [dbo].[STRUCTURE_PROVINCE_RESOURCE] WITH CHECK ADD CONSTRAINT [PROVINCE_RESOURCE_STRUCTURE_PROVINCE_RESOURCE_FK1] FOREIGN KEY (
[ProvResource]
)
REFERENCES [dbo].[PROVINCE_RESOURCE] (
[ProvResource]
)
ALTER TABLE [dbo].[STRUCTURE_PROVINCE_RESOURCE] WITH CHECK ADD CONSTRAINT [STRUCTURE_STRUCTURE_PROVINCE_RESOURCE_FK1] FOREIGN KEY (
[StructureID]
)
REFERENCES [dbo].[STRUCTURE] (
[StructureID]
)
GO

GO

ALTER TABLE [dbo].[XP_TRANSACTION] WITH CHECK ADD CONSTRAINT [CHARACTER_XP_TRANSACTION_FK1] FOREIGN KEY (
[CharacterID]
)
REFERENCES [dbo].[CHARACTER] (
[CharacterID]
)
GO

GO

ALTER TABLE [dbo].[CITY] WITH CHECK ADD CONSTRAINT [PROVINCE_CITY_FK1] FOREIGN KEY (
[ProvinceID]
)
REFERENCES [dbo].[PROVINCE] (
[ProvinceID]
)
GO

ALTER TABLE [dbo].[DISTRICT] WITH CHECK ADD CONSTRAINT [CITY_DISTRICT_FK1] FOREIGN KEY (
[CityID]
)
REFERENCES [dbo].[CITY] (
[CityID]
)
GO

GO
